"""first

Revision ID: 12ef3e4c1f2c
Revises: d8e971ddaf6c
Create Date: 2022-09-01 17:32:08.489044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ef3e4c1f2c'
down_revision = 'd8e971ddaf6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sp100Prices',
    sa.Column('date', sa.String(length=252), nullable=False),
    sa.Column('symbol', sa.String(length=252), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'symbol', 'value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sp100Prices')
    # ### end Alembic commands ###
