"""Date and Float

Revision ID: 275e4f997bf4
Revises: 5e62b22634fa
Create Date: 2022-09-05 12:13:33.903377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275e4f997bf4'
down_revision = '5e62b22634fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
