"""hello

Revision ID: 5e62b22634fa
Revises: 12ef3e4c1f2c
Create Date: 2022-09-05 12:12:34.270521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e62b22634fa'
down_revision = '12ef3e4c1f2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
