"""changing back to string

Revision ID: c393de84fb80
Revises: 275e4f997bf4
Create Date: 2022-09-05 12:23:59.587166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c393de84fb80'
down_revision = '275e4f997bf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
